# Configuración de la base de datos Oracle
spring.datasource.url: jdbc:oracle:thin:@localhost:1521/xe
spring.datasource.username: sys
spring.datasource.password: root
spring.datasource.driver-class-name: oracle.jdbc.OracleDriver
spring.jpa.show-sql: true
spring.jpa.hibernate.ddl-auto: update